on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

name: Unit Tests

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Install Dependencies
        run: make install

      - name: Build Contracts
        run: make build

      - name: Check formatting
        run: make format-check

      - name: Run Tests
        env:
          MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
          
        run: make test
