on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

name: Unit Tests

env:
  MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Build Contracts
        run: forge build --sizes

      - name: Check formatting
        run: forge fmt --check

      - name: Run Tests
        env:
          MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}

        run: forge test
